// Data Source: ProfileRemoteDataSource
// Feature: 006-user-profile (evolved from 002-profile-setup)
// Purpose: Supabase REST API integration for complete profile system

import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/profile_model.dart';
import '../models/profile_stats_model.dart';

/// Remote data source for profile operations using Supabase
///
/// Database schema: supabase/migrations/006_user_profile_system.sql
/// RLS policies: Profiles are publicly readable if profile_visible=true
class ProfileRemoteDataSource {
  final SupabaseClient _supabase;

  ProfileRemoteDataSource(this._supabase);

  /// Get current user's profile
  /// Throws [PostgrestException] on error
  Future<ProfileModel> getProfile(String userId) async {
    try {
      final response = await _supabase
          .from('profiles')
          .select()
          .eq('id', userId)
          .single();

      return ProfileModel.fromJson(response);
    } on PostgrestException catch (e) {
      if (e.code == 'PGRST116') {
        // No rows returned - profile doesn't exist
        throw ProfileNotFoundException('Profile not found for user $userId');
      }
      rethrow;
    }
  }

  /// Get another user's profile by ID (for viewing other profiles)
  /// RLS policy ensures only public profiles (profile_visible=true, deleted_at=null) are returned
  /// Throws [ProfileNotFoundException] if profile not found or not visible
  Future<ProfileModel> getProfileById(String userId) async {
    try {
      final response = await _supabase
          .from('profiles')
          .select()
          .eq('id', userId)
          .single();

      return ProfileModel.fromJson(response);
    } on PostgrestException catch (e) {
      if (e.code == 'PGRST116') {
        throw ProfileNotFoundException('Profile not found or not visible');
      }
      rethrow;
    }
  }

  /// Get user profile by username (for deep link navigation: nova://profile/{username})
  /// RLS policy ensures only public profiles are returned
  /// Throws [ProfileNotFoundException] if username not found or profile not visible
  Future<ProfileModel> getProfileByUsername(String username) async {
    try {
      final response = await _supabase
          .from('profiles')
          .select()
          .eq('username', username)
          .single();

      return ProfileModel.fromJson(response);
    } on PostgrestException catch (e) {
      if (e.code == 'PGRST116') {
        throw ProfileNotFoundException('User @$username not found');
      }
      rethrow;
    }
  }

  /// Get profile statistics (events created, participations count)
  /// Uses database function: get_profile_stats(user_id UUID)
  /// Returns ProfileStatsModel with counts (defaults to 0 if no data)
  Future<ProfileStatsModel> getProfileStats(String userId) async {
    try {
      final response = await _supabase.rpc(
        'get_profile_stats',
        params: {'user_id': userId},
      );

      // Response is a single row with events_created_count and participations_count
      if (response is List && response.isNotEmpty) {
        return ProfileStatsModel.fromJson(response.first);
      } else if (response is Map<String, dynamic>) {
        return ProfileStatsModel.fromJson(response);
      } else {
        // No data returned, return empty stats
        return ProfileStatsModel(
          eventsCreatedCount: 0,
          participationsCount: 0,
        );
      }
    } on PostgrestException catch (e) {
      throw ProfileStatsException('Failed to fetch profile stats: ${e.message}');
    }
  }

  /// Create new profile (first-time setup)
  /// Username is auto-generated by database trigger (set_username_on_signup)
  /// Throws [PostgrestException] on error (e.g., duplicate key if profile already exists)
  Future<ProfileModel> createProfile(ProfileModel profile) async {
    try {
      final response = await _supabase
          .from('profiles')
          .insert(profile.toJson())
          .select()
          .single();

      return ProfileModel.fromJson(response);
    } on PostgrestException catch (e) {
      if (e.code == '23505') {
        // Unique constraint violation - profile already exists
        throw ProfileAlreadyExistsException(
            'Profile already exists for user ${profile.id}');
      }
      rethrow;
    }
  }

  /// Update existing profile (partial updates supported)
  /// Only sends changed fields to minimize bandwidth
  /// Bio is auto-sanitized by database trigger (sanitize_bio)
  /// Throws [PostgrestException] on error
  Future<ProfileModel> updateProfile(
    String userId,
    Map<String, dynamic> updates,
  ) async {
    try {
      final response = await _supabase
          .from('profiles')
          .update(updates)
          .eq('id', userId)
          .select()
          .single();

      return ProfileModel.fromJson(response);
    } on PostgrestException catch (e) {
      if (e.code == 'PGRST116') {
        throw ProfileNotFoundException('Profile not found for user $userId');
      }
      rethrow;
    }
  }

  /// Soft delete profile (GDPR Right to Erasure)
  /// Sets deleted_at timestamp, triggering 30-day grace period
  /// Hard delete performed by database cron job after 30 days
  /// Throws [PostgrestException] on error
  Future<void> softDeleteProfile(String userId) async {
    try {
      await _supabase.from('profiles').update({
        'deleted_at': DateTime.now().toUtc().toIso8601String(),
      }).eq('id', userId);
    } on PostgrestException catch (e) {
      throw ProfileDeletionException('Failed to delete profile: ${e.message}');
    }
  }

  /// Hard delete profile immediately (admin-only, not exposed in user UI)
  /// Cascade deletes handled by database (ON DELETE CASCADE)
  /// Throws [PostgrestException] on error
  Future<void> hardDeleteProfile(String userId) async {
    await _supabase.from('profiles').delete().eq('id', userId);
  }

  /// Update profile visibility toggle (privacy setting)
  /// Sets profile_visible boolean
  Future<void> updateProfileVisibility(String userId, bool visible) async {
    try {
      await _supabase.from('profiles').update({
        'profile_visible': visible,
      }).eq('id', userId);
    } on PostgrestException catch (e) {
      throw ProfileUpdateException(
          'Failed to update profile visibility: ${e.message}');
    }
  }

  /// Export user data for GDPR compliance (Right to Access, Art. 15)
  /// Returns JSON with profile data, events created, participations, comments
  /// See spec: FR-022 GDPR Export Data
  Future<Map<String, dynamic>> exportUserData(String userId) async {
    try {
      // Fetch profile data
      final profile = await getProfile(userId);
      final stats = await getProfileStats(userId);

      // Fetch events created by user
      final eventsResponse = await _supabase
          .from('events')
          .select()
          .eq('creator_id', userId)
          .order('created_at', ascending: false);

      // Fetch participations
      final participationsResponse = await _supabase
          .from('participations')
          .select('*, events!inner(title, date)')
          .eq('user_id', userId)
          .order('created_at', ascending: false);

      // Fetch comments
      final commentsResponse = await _supabase
          .from('comments')
          .select('*, events!inner(title)')
          .eq('user_id', userId)
          .order('created_at', ascending: false);

      return {
        'exported_at': DateTime.now().toUtc().toIso8601String(),
        'profile': profile.toJson(),
        'stats': stats.toJson(),
        'events_created': eventsResponse,
        'participations': participationsResponse,
        'comments': commentsResponse,
      };
    } on PostgrestException catch (e) {
      throw ProfileExportException('Failed to export user data: ${e.message}');
    }
  }

  /// Search profiles by name, username, or class
  /// Uses case-insensitive search with ilike operator
  /// Only returns public profiles (profile_visible=true, deleted_at=null)
  /// Returns up to 20 results sorted by full_name
  Future<List<ProfileModel>> searchProfiles(String query) async {
    try {
      final searchTerm = '%${query.trim()}%';

      final response = await _supabase
          .from('profiles')
          .select()
          .or('full_name.ilike.$searchTerm,username.ilike.$searchTerm,class.ilike.$searchTerm')
          .eq('profile_visible', true)
          .is_('deleted_at', null)
          .order('full_name', ascending: true)
          .limit(20);

      return (response as List)
          .map((json) => ProfileModel.fromJson(json))
          .toList();
    } on PostgrestException catch (e) {
      throw ProfileSearchException('Failed to search profiles: ${e.message}');
    }
  }
}

/// Custom exceptions for better error handling

class ProfileNotFoundException implements Exception {
  final String message;
  ProfileNotFoundException(this.message);

  @override
  String toString() => 'ProfileNotFoundException: $message';
}

class ProfileAlreadyExistsException implements Exception {
  final String message;
  ProfileAlreadyExistsException(this.message);

  @override
  String toString() => 'ProfileAlreadyExistsException: $message';
}

class ProfileSearchException implements Exception {
  final String message;
  ProfileSearchException(this.message);

  @override
  String toString() => 'ProfileSearchException: $message';
}

class ProfileStatsException implements Exception {
  final String message;
  ProfileStatsException(this.message);

  @override
  String toString() => 'ProfileStatsException: $message';
}

class ProfileDeletionException implements Exception {
  final String message;
  ProfileDeletionException(this.message);

  @override
  String toString() => 'ProfileDeletionException: $message';
}

class ProfileUpdateException implements Exception {
  final String message;
  ProfileUpdateException(this.message);

  @override
  String toString() => 'ProfileUpdateException: $message';
}

class ProfileExportException implements Exception {
  final String message;
  ProfileExportException(this.message);

  @override
  String toString() => 'ProfileExportException: $message';
}