import '../../domain/entities/comment_report.dart';

/// CommentReportModel - Data Transfer Object
///
/// Handles JSON serialization/deserialization for comment_reports table.
/// Manages moderation workflow state with reason/status enums.
///
/// Constitutional Principle 5 (SPEC_FIRST): Data layer provides clean mapping
/// between database schema and domain entities for moderation features.
class CommentReportModel {
  final String id;
  final String commentId;
  final String reporterUserId;
  final CommentReportReason reason;
  final String? details; // Optional elaboration (max 500 chars)
  final CommentReportStatus status;
  final String? reviewedByModeratorId;
  final DateTime? reviewedAt;
  final String? moderatorNotes;
  final DateTime createdAt;

  const CommentReportModel({
    required this.id,
    required this.commentId,
    required this.reporterUserId,
    required this.reason,
    this.details,
    this.status = CommentReportStatus.pending,
    this.reviewedByModeratorId,
    this.reviewedAt,
    this.moderatorNotes,
    required this.createdAt,
  });

  // ==========================================================================
  // JSON DESERIALIZATION (Supabase → CommentReportModel)
  // ==========================================================================

  /// Create CommentReportModel from Supabase JSON response
  ///
  /// Maps snake_case database fields to camelCase Dart fields.
  /// Converts string enum values to CommentReportReason/Status enums.
  factory CommentReportModel.fromJson(Map<String, dynamic> json) {
    return CommentReportModel(
      id: json['id'] as String,
      commentId: json['comment_id'] as String,
      reporterUserId: json['reporter_user_id'] as String,
      reason: CommentReportReason.fromValue(json['reason'] as String),
      details: json['details'] as String?,
      status: CommentReportStatus.fromValue(
        json['status'] as String? ?? 'pending',
      ),
      reviewedByModeratorId: json['reviewed_by_moderator_id'] as String?,
      reviewedAt: json['reviewed_at'] != null
          ? DateTime.parse(json['reviewed_at'] as String)
          : null,
      moderatorNotes: json['moderator_notes'] as String?,
      createdAt: DateTime.parse(json['created_at'] as String),
    );
  }

  // ==========================================================================
  // JSON SERIALIZATION (CommentReportModel → JSON)
  // ==========================================================================

  /// Convert CommentReportModel to JSON for API requests
  ///
  /// Converts enum values to string for Supabase insert/update operations.
  /// Omits read-only fields (id, createdAt auto-generated by database).
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'comment_id': commentId,
      'reporter_user_id': reporterUserId,
      'reason': reason.value,
      'details': details,
      'status': status.value,
      'reviewed_by_moderator_id': reviewedByModeratorId,
      'reviewed_at': reviewedAt?.toIso8601String(),
      'moderator_notes': moderatorNotes,
      'created_at': createdAt.toIso8601String(),
    };
  }

  /// Create JSON for new report submission (excludes id/createdAt)
  ///
  /// Used when calling Supabase .insert() with auto-generated fields.
  Map<String, dynamic> toInsertJson() {
    return {
      'comment_id': commentId,
      'reporter_user_id': reporterUserId,
      'reason': reason.value,
      'details': details,
      // Status defaults to 'pending' in database
      // createdAt auto-generated by database
    };
  }

  // ==========================================================================
  // DOMAIN ENTITY CONVERSION (CommentReportModel → CommentReport)
  // ==========================================================================

  /// Convert data model to domain entity
  ///
  /// Direct mapping since both model and entity share the same structure.
  CommentReport toEntity() {
    return CommentReport(
      id: id,
      commentId: commentId,
      reporterUserId: reporterUserId,
      reason: reason,
      details: details,
      status: status,
      reviewedByModeratorId: reviewedByModeratorId,
      reviewedAt: reviewedAt,
      moderatorNotes: moderatorNotes,
      createdAt: createdAt,
    );
  }

  // ==========================================================================
  // DOMAIN ENTITY CONVERSION (CommentReport → CommentReportModel)
  // ==========================================================================

  /// Create CommentReportModel from domain entity
  ///
  /// Useful for testing or when converting cached entities.
  factory CommentReportModel.fromEntity(CommentReport entity) {
    return CommentReportModel(
      id: entity.id,
      commentId: entity.commentId,
      reporterUserId: entity.reporterUserId,
      reason: entity.reason,
      details: entity.details,
      status: entity.status,
      reviewedByModeratorId: entity.reviewedByModeratorId,
      reviewedAt: entity.reviewedAt,
      moderatorNotes: entity.moderatorNotes,
      createdAt: entity.createdAt,
    );
  }

  // ==========================================================================
  // HELPER METHODS
  // ==========================================================================

  /// Create a copy with updated fields
  ///
  /// Useful for updating report status during moderation workflow.
  CommentReportModel copyWith({
    String? id,
    String? commentId,
    String? reporterUserId,
    CommentReportReason? reason,
    String? details,
    CommentReportStatus? status,
    String? reviewedByModeratorId,
    DateTime? reviewedAt,
    String? moderatorNotes,
    DateTime? createdAt,
  }) {
    return CommentReportModel(
      id: id ?? this.id,
      commentId: commentId ?? this.commentId,
      reporterUserId: reporterUserId ?? this.reporterUserId,
      reason: reason ?? this.reason,
      details: details ?? this.details,
      status: status ?? this.status,
      reviewedByModeratorId:
          reviewedByModeratorId ?? this.reviewedByModeratorId,
      reviewedAt: reviewedAt ?? this.reviewedAt,
      moderatorNotes: moderatorNotes ?? this.moderatorNotes,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is CommentReportModel && other.id == id;
  }

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() {
    return 'CommentReportModel(id: $id, commentId: $commentId, reason: ${reason.displayName}, status: ${status.displayName})';
  }
}
