import '../../domain/entities/comment_like.dart';

/// CommentLikeModel - Data Transfer Object
///
/// Handles JSON serialization/deserialization for comment_likes table.
/// Lightweight model for tracking user likes with GDPR soft-delete support.
///
/// Constitutional Principle 5 (SPEC_FIRST): Data layer transforms Supabase
/// JSON to domain entities following clean architecture separation.
class CommentLikeModel {
  final String commentId;
  final String userId;
  final DateTime createdAt;
  final DateTime? deletedAt; // Soft delete for GDPR compliance

  const CommentLikeModel({
    required this.commentId,
    required this.userId,
    required this.createdAt,
    this.deletedAt,
  });

  // ==========================================================================
  // JSON DESERIALIZATION (Supabase → CommentLikeModel)
  // ==========================================================================

  /// Create CommentLikeModel from Supabase JSON response
  ///
  /// Maps snake_case database fields to camelCase Dart fields.
  factory CommentLikeModel.fromJson(Map<String, dynamic> json) {
    return CommentLikeModel(
      commentId: json['comment_id'] as String,
      userId: json['user_id'] as String,
      createdAt: DateTime.parse(json['created_at'] as String),
      deletedAt: json['deleted_at'] != null
          ? DateTime.parse(json['deleted_at'] as String)
          : null,
    );
  }

  // ==========================================================================
  // JSON SERIALIZATION (CommentLikeModel → JSON)
  // ==========================================================================

  /// Convert CommentLikeModel to JSON for API requests
  ///
  /// Used when posting new likes to Supabase (createdAt auto-generated by DB).
  Map<String, dynamic> toJson() {
    return {
      'comment_id': commentId,
      'user_id': userId,
      'created_at': createdAt.toIso8601String(),
      'deleted_at': deletedAt?.toIso8601String(),
    };
  }

  // ==========================================================================
  // DOMAIN ENTITY CONVERSION (CommentLikeModel → CommentLike)
  // ==========================================================================

  /// Convert data model to domain entity
  ///
  /// Direct mapping since CommentLike and CommentLikeModel have same structure.
  CommentLike toEntity() {
    return CommentLike(
      commentId: commentId,
      userId: userId,
      createdAt: createdAt,
      deletedAt: deletedAt,
    );
  }

  // ==========================================================================
  // DOMAIN ENTITY CONVERSION (CommentLike → CommentLikeModel)
  // ==========================================================================

  /// Create CommentLikeModel from domain entity
  ///
  /// Useful for testing or caching scenarios.
  factory CommentLikeModel.fromEntity(CommentLike entity) {
    return CommentLikeModel(
      commentId: entity.commentId,
      userId: entity.userId,
      createdAt: entity.createdAt,
      deletedAt: entity.deletedAt,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;

    return other is CommentLikeModel &&
        other.commentId == commentId &&
        other.userId == userId;
  }

  @override
  int get hashCode => Object.hash(commentId, userId);

  @override
  String toString() {
    return 'CommentLikeModel(commentId: $commentId, userId: $userId, createdAt: $createdAt)';
  }
}
